# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 850b396cb8540846bb18905eae600b66d7db28dd1b364c937d0346bc85433a16db4ad8a60b19bf8a4a086f20e970b3c1e6f83c4d54ca025b811821288e5ff756

test:
  secret_key_base: ab828d3dfe298bf976f9a9f85bd94de3cdd8b6aa6bdf229d2f43c79aab18f7afcf790fb1f0cad772587edabb9db1952478876ca6a19308ec3a0a1602baddf7ec

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
